jvmOpts: "-Xms512m -Xmx1g"
client:
  serverUrl: "ws://54.189.110.165:8080/chat"
  totalMessages: 500000
  warmupThreads: 32
  warmupMessagesPerThread: 1000
  connectionsPerRoom: 1
  handshakeTimeoutSeconds: 20
  maxConcurrentHandshakes: 6
  handshakeRetryDelayMs: 10
  responseWaitSeconds: 30
  batchSize: 100
  batchMaxBytes: 65536
  flushIntervalMs: 2
  flushSync: true
