jvmOpts: "-Xms512m -Xmx1g"
client:
  serverUrl: "ws://35.87.16.91:8080/chat"
  totalMessages: 500000
  warmupThreads: 32
  warmupMessagesPerThread: 1000
  mainThreads: 16
  targetQps: 40000
  connectionsPerRoom: 1
  handshakeTimeoutSeconds: 20
  maxConcurrentHandshakes: 12
  handshakeRetryDelayMs: 10
  responseWaitSeconds: 30
  batchSize: 100
  batchMaxBytes: 65536
  flushIntervalMs: 5
  flushSync: false
