jvmOpts: "-Xms512m -Xmx1g"
client:
  serverUrl: "ws://54.245.136.79:8080/chat"
  totalMessages: 5000000
  warmupThreads: 32
  warmupMessagesPerThread: 1000
  mainThreads: 32
  targetQps: 60000
  connectionsPerRoom: 1
  handshakeTimeoutSeconds: 20
  maxConcurrentHandshakes: 24
  handshakeRetryDelayMs: 10
  responseWaitSeconds: 30
  batchSize: 100
  batchMaxBytes: 65536
  flushIntervalMs: 5
  flushSync: false
