jvmOpts: "-Xms512m -Xmx1g"
client:
  serverUrl: "ws://35.85.60.60:8080/chat"
  totalMessages: 500000
  warmupThreads: 32
  warmupMessagesPerThread: 1000
  mainThreads: 16
  targetQps: 100000
  connectionsPerRoom: 1
  handshakeTimeoutSeconds: 20
  maxConcurrentHandshakes: 48
  handshakeRetryDelayMs: 10
  responseWaitSeconds: 30
  batchSize: 100
  batchMaxBytes: 65536
  flushIntervalMs: 2
  flushSync: false
